package com.etulasetu.enums;

public enum InstrumentCategory {
    WATER_METER,
    SPHYGMOMANOMETER,
    CLINICAL_THERMOMETER,
    RAIL_WEIGHBRIDGE,
    TAPE_MEASURE,
    NON_AUTO_CLASS_III,
    NON_AUTO_CLASS_IIII,
    LOAD_CELL,
    BEAM_SCALE,
    COUNTER_MACHINE,
    WEIGHT,
    LPG_DISPENSER,
    CNG_DISPENSER,
    VOLUMETRIC,
    TAXI_METER,
    FLOW_METER,
    AUTOMATIC_WEIGHING,
    LINEAR_MEASURING,
    CAPACITY_MEASURE,
    OTHER
}
